# 在这里填写主人
master:
  - "114514"
  - "可填多个"
# 填写拥有完全控制权限的超级用户
superusers:
  - "114514"
  - "可填多个"
# 填写使用的端口
port: 1451
# 填写命令前缀
command_start:
  - "/"
  - "#"
  - "无语"
# 命令分割符
command_sep: 
  - " "
  - "."
# 日志等级
log_level: "INFO"
# 图片外显
pic-summary: "Jerry来了"
# 其他设置
others:
  - "实例":"值"

